package goldbigdragon.github.io.function.alarm.enums;

public enum BeforeWorkType {
    CREATE_CRIMINALSTATISTICSANALYSIS_DEFAULT_MODEL,
    CREATE_FLUCTUATED_DATA,
    OVERWRITE_CRIMINALSTATISTICSANALYSIS_MODEL,
    OVERWRITE_CRIMINALSTATISTICSANALYSIS_DATA,
    LOAD_CRIMINALSTATISTICSANALYSIS_DATABASE,
    CALCULATE_CRIMINALSTATISTICSANALYSIS
    ;
}
